import "bootstrap/dist/css/bootstrap.min.css"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
//Components
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Listar Números',
  description: 'Generated by create next app',
  icons:'../../public/calculadora.png',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className="d-flex flex-column min-vh-100">
        <Navbar/>
        {children}      
        <Footer/>
      </body>
    </html>
  )
}
